# Generated by Django 2.0.6 on 2019-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=500, null=True)),
                ('visitor_phone', models.BigIntegerField()),
                ('visitor_email', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='CHECKED_IN', max_length=10)),
                ('checkin_time', models.DateTimeField(auto_now=True)),
                ('checkout_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=500, null=True)),
                ('host_phone', models.BigIntegerField()),
                ('host_email', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
